import { useEffect, useState } from "react";
import Button from "../../components/Button";
import Alert from "../../components/Alert";
import { api } from "../../services/api";

const blank = { name: "", description: "", price: "", category: "", stock: "" };
export default function AdminPage() {
  const [tab, setTab] = useState("products"); const [products, setProducts] = useState([]); const [orders, setOrders] = useState([]); const [users, setUsers] = useState([]); const [reviews, setReviews] = useState([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = async () => { try { const [productData, orderData, userData, reviewData] = await Promise.all([api.products(), api.orders(), api.users(), api.allReviews()]); setProducts(Array.isArray(productData) ? productData : productData.products || []); setOrders(Array.isArray(orderData) ? orderData : orderData.orders || []); setUsers(Array.isArray(userData) ? userData : userData.users || []); setReviews(Array.isArray(reviewData) ? reviewData : reviewData.reviews || []); } catch (err) { setError(err.message); } };
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer); }, []);
  const submitProduct = async (event) => { event.preventDefault(); setError(""); try { if (editing) await api.updateProduct(editing, { ...form, price: Number(form.price), stock: Number(form.stock) }); else await api.createProduct({ ...form, price: Number(form.price), stock: Number(form.stock) }); setForm(blank); setEditing(null); setMessage("Product saved."); load(); } catch (err) { setError(err.message); } };
  const editProduct = (product) => { setEditing(product._id || product.id); setForm({ name: product.name || "", description: product.description || "", price: product.price || "", category: product.category?.name || product.category || "", stock: product.stock ?? product.quantity ?? "" }); };
  const updateOrder = async (id, status) => { try { await api.updateOrder(id, { status }); setMessage("Order status updated."); load(); } catch (err) { setError(err.message); } };
  const updateUser = async (id, active) => { try { await api.updateUser(id, { isActive: active }); setMessage("User updated."); load(); } catch (err) { setError(err.message); } };
  const updateReview = async (review) => { const comment = window.prompt("Edit review", review.comment || review.review || ""); if (comment === null) return; try { await api.updateReview(review._id || review.id, { comment }); setMessage("Review updated."); load(); } catch (err) { setError(err.message); } };
  const tabs = ["products", "orders", "reviews", "users"];
  return <section className="mx-auto max-w-6xl px-4 py-8"><h1 className="text-3xl font-bold">Admin dashboard</h1><div className="mt-4 flex gap-2">{tabs.map((item) => <Button key={item} onClick={() => setTab(item)} variant={tab === item ? "primary" : "secondary"}>{item}</Button>)}</div><div className="mt-4"><Alert>{error}</Alert><Alert type="success">{message}</Alert></div>
    {tab === "products" && <div className="mt-5 grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={submitProduct} className="grid h-fit gap-3 rounded-xl border-2 border-blue-900 bg-blue-100 p-4"><h2 className="text-xl font-bold">{editing ? "Edit product" : "Create product"}</h2>{Object.keys(blank).map((field) => <label key={field} className="capitalize">{field}<input required type={field === "price" || field === "stock" ? "number" : "text"} className="mt-1 w-full rounded border p-2" value={form[field]} onChange={(e) => setForm({ ...form, [field]: e.target.value })} /></label>)}<Button type="submit" variant="primary">Save product</Button></form><div className="space-y-3">{products.map((item) => <article key={item._id || item.id} className="flex justify-between rounded-xl border p-4"><span>{item.name} — ₱{item.price}</span><Button onClick={() => editProduct(item)}>Edit</Button></article>)}</div></div>}
    {tab === "orders" && <div className="mt-5 space-y-3">{orders.map((order) => <article key={order._id || order.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><span>#{order.orderNumber || order._id || order.id} · {order.status}</span><div className="flex gap-2"><Button onClick={() => updateOrder(order._id || order.id, "confirmed")}>Confirm</Button><Button variant="primary" onClick={() => updateOrder(order._id || order.id, "ready for claiming")}>Ready</Button></div></article>)}</div>}
    {tab === "reviews" && <div className="mt-5 space-y-3">{reviews.map((review) => <article key={review._id || review.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><span>{"★".repeat(review.rating || 0)} {review.comment || review.review} — {review.user?.name || review.userName || "Customer"}</span><Button onClick={() => updateReview(review)}>Edit</Button></article>)}</div>}
    {tab === "users" && <div className="mt-5 space-y-3">{users.map((account) => <article key={account._id || account.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><span>{account.name || `${account.firstName || ""} ${account.lastName || ""}`} · {account.email} · {account.role}</span><Button onClick={() => updateUser(account._id || account.id, !(account.isActive ?? account.active))}>{(account.isActive ?? account.active) ? "Set inactive" : "Set active"}</Button></article>)}</div>}
  </section>;
}
