import express from "express";
import cors from "cors";
import authRoutes from "./routes/auth.js";
import productRoutes from "./routes/products.js";
import orderRoutes from "./routes/orders.js";
import reviewRoutes, { productReviewRouter } from "./routes/reviews.js";
import userRoutes from "./routes/users.js";

const app = express();
app.use(cors({ origin: process.env.CLIENT_URL || "http://localhost:5177" }));
app.use(express.json({ limit: "1mb" }));
app.use("/uploads", express.static("uploads"));
app.get("/api/health", (_req, res) => res.json({ message: "Bulldogs Exchange API is running." }));
app.use("/api/auth", authRoutes);
app.use("/api/products", productRoutes);
app.use("/api/products/:id/reviews", productReviewRouter);
app.use("/api/orders", orderRoutes);
app.use("/api/reviews", reviewRoutes);
app.use("/api/users", userRoutes);
app.use((_req, res) => res.status(404).json({ message: "Route not found." }));
app.use((error, _req, res, _next) => { console.error(error); if (error.name === "MulterError") return res.status(400).json({ message: "Image upload failed. Images must be 5 MB or smaller." }); if (error.name === "ValidationError") return res.status(400).json({ message: Object.values(error.errors).map((item) => item.message).join(" ") }); if (error.name === "CastError") return res.status(404).json({ message: "Record not found." }); if (error.message?.includes("image files")) return res.status(400).json({ message: error.message }); res.status(500).json({ message: "Server error. Please try again." }); });
export default app;
